apiVersion: v1
kind: Service
metadata:
 name: demo-service
spec:
 selector:
   app: nginx
 type:  LoadBalancer
 ports:
 - name:  http
   port:  8080    # 外部 IP 的 Port
   targetPort: 80 # Container 對應到的 Port
   protocol: TCP  # optional protocol


